// <auto-generated />
using System;
using CatechistHelper.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatechistHelper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009120929_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("account");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.BudgetTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<double>("FromBudget")
                        .HasColumnType("float")
                        .HasColumnName("from_budget");

                    b.Property<double>("ToBudget")
                        .HasColumnType("float")
                        .HasColumnName("to_budget");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("budget_transaction");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Catechist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("birth_place");

                    b.Property<Guid>("ChristianNameId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("christian_name_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("father_name");

                    b.Property<string>("FatherPhone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("father_phone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTeaching")
                        .HasColumnType("bit")
                        .HasColumnName("is_teaching");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("level_id");

                    b.Property<string>("MotherName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mother_name");

                    b.Property<string>("MotherPhone")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("mother_phone");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("qualification");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("ChristianNameId");

                    b.HasIndex("LevelId");

                    b.ToTable("catechist");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInClass", b =>
                {
                    b.Property<Guid>("CatechistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catechist_id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("class_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_main");

                    b.HasKey("CatechistId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("catechist_in_class");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInGrade", b =>
                {
                    b.Property<Guid>("CatechisteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catechist_id");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_main");

                    b.HasKey("CatechisteId", "GradeId");

                    b.HasIndex("GradeId");

                    b.ToTable("catechist_in_grade");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInSlot", b =>
                {
                    b.Property<Guid>("CatechistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catechist_id");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slot_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_main");

                    b.HasKey("CatechistId", "SlotId");

                    b.HasIndex("SlotId");

                    b.ToTable("catechist_in_slot");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInTraining", b =>
                {
                    b.Property<Guid>("CatechistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catechist_id");

                    b.Property<Guid>("TrainingListId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_list_id");

                    b.Property<byte>("CatechistInTrainingStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("CatechistId", "TrainingListId");

                    b.HasIndex("TrainingListId");

                    b.ToTable("catechist_in_training");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("level_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("certificate");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CertificateOfCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("certificate_of_candidate");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CertificateOfCatechist", b =>
                {
                    b.Property<Guid>("CatechistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("catechist_id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<DateTime>("GrantedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("granted_date");

                    b.HasKey("CatechistId", "CertificateId");

                    b.HasIndex("CertificateId");

                    b.ToTable("certificate_of_catechist");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.ChristianName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("HolyDay")
                        .HasColumnType("datetime2")
                        .HasColumnName("holy_day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("christian_name");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte>("ClassStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("NumberOfCatechist")
                        .HasColumnType("int")
                        .HasColumnName("number_of_catechist");

                    b.Property<Guid>("PastoralYearId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pastoral_year_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("PastoralYearId");

                    b.ToTable("class");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<byte>("EventStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<bool>("IsCheckedIn")
                        .HasColumnType("bit")
                        .HasColumnName("is_checked_in");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPeriodic")
                        .HasColumnType("bit")
                        .HasColumnName("is_periodic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<double>("current_budget")
                        .HasColumnType("float")
                        .HasColumnName("cuurent_budget");

                    b.HasKey("Id");

                    b.ToTable("event");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("major_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("PastoralYearId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pastoral_year_id");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.HasIndex("PastoralYearId");

                    b.ToTable("grade");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit")
                        .HasColumnName("is_passed");

                    b.Property<DateTime>("MeetingTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("meeting_time");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_id");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("interview");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.InterviewProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("interview_process");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CatechismLevel")
                        .HasColumnType("int")
                        .HasColumnName("catechism_level");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("level");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("major");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<Guid>("RoleEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_event_id");

                    b.HasKey("AccountId", "EventId");

                    b.HasIndex("EventId");

                    b.HasIndex("RoleEventId");

                    b.ToTable("member");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.MemberOfProcess", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("process_id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit")
                        .HasColumnName("is_main");

                    b.HasKey("AccountId", "ProcessId");

                    b.HasIndex("ProcessId");

                    b.ToTable("member_of_process");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.ParticipantInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("bit")
                        .HasColumnName("is_attended");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("participant_in_event");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.PastoralYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<byte>("PastoralYearStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("pastoral_year");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module");

                    b.Property<Guid>("PostCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_category_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PostCategoryId");

                    b.ToTable("post");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.PostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("post_category");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time")
                        .HasColumnName("duration");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<double>("Fee")
                        .HasColumnType("float")
                        .HasColumnName("fee");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("process");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Recruiter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registration_id");

                    b.HasKey("AccountId", "RegistrationId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("recruiter");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fullname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsTeachingBefore")
                        .HasColumnType("bit")
                        .HasColumnName("is_teaching_before");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("YearOfTeaching")
                        .HasColumnType("int")
                        .HasColumnName("year_of_teaching");

                    b.HasKey("Id");

                    b.ToTable("registration");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.RoleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("role_event");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("room");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("room");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RoomId");

                    b.ToTable("slot");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("system_configuration");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.TeachingQualification", b =>
                {
                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("level_id");

                    b.Property<Guid>("MajorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("major_id");

                    b.HasKey("LevelId", "MajorId");

                    b.HasIndex("MajorId");

                    b.ToTable("teaching_qualification");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.TrainingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NextLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("next_level");

                    b.Property<string>("PreviousLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("previous_level");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time");

                    b.Property<byte>("TrainingListStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("training_list");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Account", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.BudgetTransaction", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Event", "Event")
                        .WithMany("BudgetTransactions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Catechist", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Account", "Account")
                        .WithOne("Catechist")
                        .HasForeignKey("CatechistHelper.Domain.Entities.Catechist", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.ChristianName", "ChristianName")
                        .WithMany("Catechists")
                        .HasForeignKey("ChristianNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Level", "Level")
                        .WithMany("Catechists")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("ChristianName");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInClass", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Catechist", "Catechist")
                        .WithMany("CatechistInClasses")
                        .HasForeignKey("CatechistId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Class", "Class")
                        .WithMany("CatechistInClasses")
                        .HasForeignKey("ClassId")
                        .IsRequired();

                    b.Navigation("Catechist");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInGrade", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Catechist", "Catechist")
                        .WithMany("CatechistInGrades")
                        .HasForeignKey("CatechisteId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Grade", "Grade")
                        .WithMany("CatechistInGrades")
                        .HasForeignKey("GradeId")
                        .IsRequired();

                    b.Navigation("Catechist");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInSlot", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Catechist", "Catechist")
                        .WithMany("CatechistInSlots")
                        .HasForeignKey("CatechistId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Slot", "Slot")
                        .WithMany("CatechistInSlots")
                        .HasForeignKey("SlotId")
                        .IsRequired();

                    b.Navigation("Catechist");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CatechistInTraining", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Catechist", "Catechist")
                        .WithMany("CatechistInTrainings")
                        .HasForeignKey("CatechistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.TrainingList", "TrainingList")
                        .WithMany("CatechistInTrainings")
                        .HasForeignKey("TrainingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catechist");

                    b.Navigation("TrainingList");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Level", "Level")
                        .WithMany("Certificates")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CertificateOfCandidate", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Registration", "Registration")
                        .WithMany("CertificateOfCandidates")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.CertificateOfCatechist", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Catechist", "Catechist")
                        .WithMany("CertificateOfCatechists")
                        .HasForeignKey("CatechistId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Certificate", "Certificate")
                        .WithMany("CertificateOfCatechists")
                        .HasForeignKey("CertificateId")
                        .IsRequired();

                    b.Navigation("Catechist");

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Class", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.PastoralYear", "PastoralYear")
                        .WithMany("Classes")
                        .HasForeignKey("PastoralYearId")
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("PastoralYear");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Grade", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Major", "Major")
                        .WithMany("Grades")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.PastoralYear", "PastoralYear")
                        .WithMany("Grades")
                        .HasForeignKey("PastoralYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("PastoralYear");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Interview", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Registration", "Registration")
                        .WithMany("Interviews")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.InterviewProcess", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Registration", "Registration")
                        .WithMany("InterviewProcesses")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Member", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Account", "Account")
                        .WithMany("Members")
                        .HasForeignKey("AccountId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Event", "Event")
                        .WithMany("Members")
                        .HasForeignKey("EventId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.RoleEvent", "RoleEvent")
                        .WithMany("Members")
                        .HasForeignKey("RoleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Event");

                    b.Navigation("RoleEvent");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.MemberOfProcess", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Account", "Account")
                        .WithMany("MemberOfProcesses")
                        .HasForeignKey("AccountId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Process", "Process")
                        .WithMany("MemberOfProcesses")
                        .HasForeignKey("ProcessId")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Process");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.ParticipantInEvent", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Event", "Event")
                        .WithMany("ParticipantInEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Post", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.PostCategory", "PostCategory")
                        .WithMany("Posts")
                        .HasForeignKey("PostCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PostCategory");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Process", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Event", "Event")
                        .WithMany("Processes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Recruiter", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Account", "Account")
                        .WithMany("Recruiters")
                        .HasForeignKey("AccountId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Registration", "Registration")
                        .WithMany("Recruiters")
                        .HasForeignKey("RegistrationId")
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Slot", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Class", "Class")
                        .WithMany("Slots")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Room", "Room")
                        .WithMany("Slots")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.TeachingQualification", b =>
                {
                    b.HasOne("CatechistHelper.Domain.Entities.Level", "Level")
                        .WithMany("TeachingQualifications")
                        .HasForeignKey("LevelId")
                        .IsRequired();

                    b.HasOne("CatechistHelper.Domain.Entities.Major", "Major")
                        .WithMany("TeachingQualifications")
                        .HasForeignKey("MajorId")
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Major");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Account", b =>
                {
                    b.Navigation("Catechist");

                    b.Navigation("MemberOfProcesses");

                    b.Navigation("Members");

                    b.Navigation("Posts");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Catechist", b =>
                {
                    b.Navigation("CatechistInClasses");

                    b.Navigation("CatechistInGrades");

                    b.Navigation("CatechistInSlots");

                    b.Navigation("CatechistInTrainings");

                    b.Navigation("CertificateOfCatechists");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Certificate", b =>
                {
                    b.Navigation("CertificateOfCatechists");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.ChristianName", b =>
                {
                    b.Navigation("Catechists");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Class", b =>
                {
                    b.Navigation("CatechistInClasses");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Event", b =>
                {
                    b.Navigation("BudgetTransactions");

                    b.Navigation("Members");

                    b.Navigation("ParticipantInEvents");

                    b.Navigation("Processes");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Grade", b =>
                {
                    b.Navigation("CatechistInGrades");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Level", b =>
                {
                    b.Navigation("Catechists");

                    b.Navigation("Certificates");

                    b.Navigation("TeachingQualifications");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Major", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("TeachingQualifications");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.PastoralYear", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.PostCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Process", b =>
                {
                    b.Navigation("MemberOfProcesses");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Registration", b =>
                {
                    b.Navigation("CertificateOfCandidates");

                    b.Navigation("InterviewProcesses");

                    b.Navigation("Interviews");

                    b.Navigation("Recruiters");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.RoleEvent", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Room", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.Slot", b =>
                {
                    b.Navigation("CatechistInSlots");
                });

            modelBuilder.Entity("CatechistHelper.Domain.Entities.TrainingList", b =>
                {
                    b.Navigation("CatechistInTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
